@base_url=http://localhost:8081

DELETE {{base_url}}/todos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJLaXR0YW1ldCIsImV4cCI6MTcxMjM5MjQxMn0.FXaOgcT7lyG921Qk9qEHjPQfwAjcABkFhy-_iA2XOqk